"""new

Revision ID: 223b560b220c
Revises: ef628984c0a8
Create Date: 2019-10-02 04:06:10.522312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223b560b220c'
down_revision = 'ef628984c0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('event_timeEnd', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('event_timeStart', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'event_timeStart')
    op.drop_column('user', 'event_timeEnd')
    op.drop_column('user', 'event_date')
    # ### end Alembic commands ###
