"""new fields

Revision ID: ef628984c0a8
Revises: c070e82e80fa
Create Date: 2019-10-02 03:21:37.308794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef628984c0a8'
down_revision = 'c070e82e80fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('event', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'event')
    # ### end Alembic commands ###
